Bitergia/prosoul

- django_meditor/meditor/forms_editor.py
- django_meditor/meditor/meditor_assess.py
- django_meditor/meditor/models.py
- django_meditor/meditor/templates/meditor/editor_metric.html
- django_meditor/meditor/views_editor.py
This PR adds a new tool to assess a project. It includes also all the support needed for including thresholds inside the metrics.
> Meditor assess tool

- django_meditor/meditor/forms.py
- django_meditor/meditor/meditor_assess.py
- django_meditor/meditor/templates/meditor/assessment.html
- django_meditor/meditor/templates/meditor/assessment_config.html
- django_meditor/meditor/templates/meditor/visualize.html
- django_meditor/meditor/urls.py
- django_meditor/meditor/views.py
It includes all the needed gui to configure and start the assessment process.
With the results it shows a report for all projects according to the attributes in the quality model.
> Add assessment feature to meditor

- CONTRIBUTING.md
> [doc] Add initial version of CONTRIBUTING.md based on AngularJS one

- .travis.yml
- django_meditor/manage.py
- django_meditor/meditor/data_editor.py
- django_meditor/meditor/forms.py
- django_meditor/meditor/forms_editor.py
- django_meditor/meditor/meditor_assess.py
- django_meditor/meditor/meditor_export.py
- django_meditor/meditor/meditor_import.py
- django_meditor/meditor/meditor_vis.py
- django_meditor/meditor/models.py
- django_meditor/meditor/views.py
- django_meditor/meditor/views_editor.py
- metrics/metrics2es.py
- setup.cfg
* Fixed all flake8 issues and configure flake8 with setup.py file
* Add .travis.yml file
> Travis initial state

- django_prosoul/prosoul/data/developer_model.json
- django_prosoul/prosoul/prosoul_export.py
- django_prosoul/prosoul/prosoul_import.py
Implements https://github.com/Bitergia/prosoul/issues/16
> Support Threshold and Metrics data in Quality Models

- django_prosoul/prosoul/views_editor.py
Fix when adding a goal that already exists
> [editor] Fix error adding a new goal that already exists (II)

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/prosoul_metrics.py
This tool helps in the understanding of the values of metrics inside projects in order to adjust thresholds.
> Add Metrics tool

- .travis.yml
- django-prosoul/prosoul/data/developer_model_grimoirelab_eclipse.json
- django-prosoul/prosoul/data/developer_model_grimoirelab_linuxfoundation2018.json
- django-prosoul/prosoul/data/developer_model_grimoirelab_mozilla.json
- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/prosoul_metrics.py
Add options to plot the final score for all projects, and to create a CSV file with the assessment so it can be analyzed in an spreadsheet.
> Assess analysis

- django-prosoul/prosoul/prosoul_vis.py
> [vis] Create alias for viz index patterns and fix fetch_dashboard kidash call to use the new API

- django-prosoul/prosoul/data.py
- django-prosoul/prosoul/prosoul_vis.py
- django-prosoul/prosoul/views.py
> [viz] Support the loading of templates from files inside the pip package

- django-prosoul/prosoul/prosoul_vis.py
- django-prosoul/prosoul/views.py
For doing it, during the viz of a quality model, the assessment
is done and the dashboard to show it is loaded and added to the menu.
> [viz] Add the assessment viz

- django-prosoul/django_prosoul/settings.py
- django-prosoul/django_prosoul/urls.py
- django-prosoul/prosoul/models.py
- django-prosoul/prosoul/rest.py
- django-prosoul/prosoul/tests.py
- django-prosoul/prosoul/urls.py
- django-prosoul/setup.py
It is based on Django REST Framework.
> [rest] Add experimental API REST support for quality models

- django-prosoul/prosoul/data/qmodel_Sentiment.json
This code includes a possible model for sentiment analysis.
> [model] Add sentiment model

- django-prosoul/config_deployment.py
- docker/stage
This code fixes the way of automatically settings the allowed hosts from the environment variables declared in the docker-compose.
> [deployment] Fix stage file

- django-prosoul/django_prosoul/settings.py
This code includes the static files needed to show the tree-based editor in prosoul.
> [django-prosoul] Add static files

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/views.py
This code fixes the names of the attributes listed in summary table prompted after the assessment.
> [views] Fix summary table for assessment

- django-prosoul/prosoul/forms.py
> Remove URL validator in assessment page in order to put docker tags

- django-prosoul/prosoul/static/prosoul/models/qmodel_crossminer.json
This code includes a qm defined using the data retrieved from crossminer.
> [models] Add example of qm tailored to crossminer data

- docker/docker-compose.yml
This code updates the docker-compose which is now using bitergia/prosoul. Furthermore
it also includes some new env variables.
> [docker] Update docker-compose

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/views.py
When the assessment is done, as the same time that the table is being built, a CSV file is being created inside the static dir, so with just a link to a button in the Assessment view, we can download this CSV.
> Add button to export the assessment in a CSV file

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/urls.py
- django-prosoul/prosoul/views.py
> Download CSV file from the backend instead from the front end

- django-prosoul/prosoul/urls.py
- django-prosoul/prosoul/views.py
Now there is a button at the top of each project assessment table in order to download just the CSV of that project.
Moreover, it is possible to download the CSV file by the following url:
`https://<prosoul_url>/download_project_assesment_csv/<project_name>` - to download the assesment of a project
`https://<prosoul_url>/download_assessment_csv` - to download all the assessments
> Download assessment by project using a button or the URL

- django-prosoul/prosoul/prosoul_assess.py
This code fixes the from_date and to_date values to make it compatible with the format expected from the ES query (yyyy-mm-dd).
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
> [prosoul_assess] Fix from and to dates to avoid ES error

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/views.py
> Move CSV creation logic to prosoul_assess.py and trigger when init

- django-prosoul/django_prosoul/templates/base.html
- django-prosoul/prosoul/prosoul_export.py
- django-prosoul/prosoul/views.py
- django-prosoul/prosoul/views_editor.py
> Add users logic to prosoul quality models

- django-prosoul/prosoul/templates/prosoul/viewer_js.html
> Fix problem with ' and " in the quality model strings

- django-prosoul/prosoul/views_editor.py
This PR fixes https://github.com/crossminer/scava-deployment/issues/50
> Add metric datas increasing the last id added

- django-prosoul/prosoul/prosoul_assess.py
This code adds some docs to better explain how metrics and attributes are calculated.
> [prosoul_assess] Add doc how metrics and attributes are calculated

- django-prosoul/prosoul/prosoul_assess.py
This code adds some docs to better explain the content of the score index generated by prosoul.
> [prosoul_assess] Add doc about items score index

- django-prosoul/prosoul/templates/prosoul/viewer_js.html
> Add tooltip when the names on the tree are too large

- django-prosoul/prosoul/data/qmodel_crossminer.json
- django-prosoul/prosoul/data/qmodel_crossminer_v0.json
This code includes a very simple quality models composed of two goals, community and activity. The former aims at measuring the community of a project based on the number of new and active users. The latter focuses on the activity of a project defined as the number of fixed bugs and patches
submitted.
> [quality model] Upload very simple qm model

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/models.py
- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/prosoul_export.py
- django-prosoul/prosoul/prosoul_import.py
- django-prosoul/prosoul/templates/prosoul/editor_metric.html
- django-prosoul/prosoul/views_editor.py
By default, the calculation type will be **max**
> Add min/max/avg/median calculation types in metrics

- django-prosoul/prosoul/views.py
> Add new env in order to fix the link when assess/visualize

- django-prosoul/prosoul/prosoul_import.py
- django-prosoul/prosoul/templates/prosoul/viewer_js.html
> Show description in the viewer tab when clicking a node

- django-prosoul/prosoul/data/qmodel_crossminer.json
- django-prosoul/prosoul/data/qmodel_crossminer_v1.json
The new quality model is composed of two goals: community and activity, the former aims at measuring
the community by focusing on user (avg of active and new users) and discussions (number of replies and comments); the latter measures the activity defined as the number of bugs and commits.
> [quality model] Update qm model

- django-prosoul/prosoul/forms_editor.py
This code adds the Sum to the list of aggregators provided by Prosoul.
> [prosoul-forms-editor] Add Sum aggregator

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/views.py
> Add calculation type to ES index and assessment view/csv

- django-prosoul/prosoul/views.py
> Fix bug when showing the calculation type in the table

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
> Show 0 value in the assessment tree

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/views.py
> Add raw value to ES index, assessment table and assessment tree

- django-prosoul/prosoul/prosoul_assess.py
This code improves the log message for missing metric values, it includes the time range to ease debugging operation with the data.
> [prosoul_assess] Improve log message for missing metric values

- django-prosoul/prosoul/views_editor.py
> Force user to put 5 int thresholds

- django-prosoul/prosoul/views_editor.py
This code changes the way the metric names are retrieved, in order to improve efficiency. The solution implemented relies on an aggregation over the attribute `metric_name`.
> [prosoul-views_editor] Use aggregations to get metric names

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/models.py
- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/prosoul_export.py
- django-prosoul/prosoul/prosoul_import.py
- django-prosoul/prosoul/templates/prosoul/editor_metric.html
- django-prosoul/prosoul/views_editor.py
> Add reverse thresholds field

- django-prosoul/prosoul/views_editor.py
> Delete quality model and its goals, attrs and metrics

- .travis.yml
This code removes the commented section install
> [travis] Remove commented section

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
> Round assessment to 2 decimals

- django-prosoul/prosoul/views_editor.py
> Redirect to the imported quality model

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
> Fix bug when showing the tree assessment values of a project

- django-prosoul/prosoul/templates/prosoul/viewer_js.html
> Hide or show children when a node of the diagram is clicked

- django-prosoul/django_prosoul/templates/base.html
- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/templates/base.html
- django-prosoul/prosoul/templates/prosoul/editor_metric.html
> Add search functionality to the metric data form select

- django-prosoul/prosoul/views_editor.py
> Change name for name plus id in metric data dropwdown form

- django-prosoul/prosoul/views_editor.py
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
> [views_editor] Fix flake8

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/views_editor.py
> Fix bug when assessment by name+id

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/views.py
This commit delete the tables that used to show the old data of
the assessment.
> [assessment] Delete projects assessment tables due to old data

- README.md
I was just going through the project and I found some typos. So, I thought I will send a PR.
Please let me know if I have to revert back anything or add anything extra.
> [docs] fixed minor typos in README.md

- README.md
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
> [doc] Add mention to CROSSMINER

- README.md
This PR adds information about the Youtube video which has the steps for installing Prosoul from the source code to the README.
I hope the formatting is clear and the information is sufficient. :slightly_smiling_face: 
@valeriocos, please review this PR when you are free.
> [docs] Update README.md with installation video

- django-prosoul/prosoul/views.py
This PR updates the Kibana dashboard URL of the result after prosoul visualization.
Fixes #205.
> [views] update the viz result kibana_url

- README.md
- doc/README.md
This PR revamps the existing README structure and moved a few contents inside doc folder.
Ref: #197 
[Link](https://github.com/vchrombie/prosoul/tree/revamp-readme) to view the changes.
> [docs] Revamp README.md
