Bitergia/prosoul

- django_meditor/meditor/forms_editor.py
- django_meditor/meditor/templates/meditor/editor_attributes.html
- django_meditor/meditor/templates/meditor/editor_goals.html
- django_meditor/meditor/templates/meditor/editor_metrics.html
- django_meditor/meditor/views_editor.py
In all the select widgets, the form is automatically sent when an option
is selected. If a selected option is clicked, it will be deselected.
> [editor] Send select forms with click and unselect option clicking on a selected one

- django_prosoul/prosoul/forms_editor.py
- django_prosoul/prosoul/models.py
- django_prosoul/prosoul/templates/prosoul/editor_metric.html
- django_prosoul/prosoul/templates/prosoul/editor_scope.html
- django_prosoul/prosoul/views_editor.py
This is a feature needed to implement the clone of quality models.
The metrics names must be unique and also the quality models name.
> [editor] Support several different goals and attributes with the same name

- django-prosoul/prosoul/prosoul_export.py
- django-prosoul/prosoul/tests.py
These formats don't include this fields.
Also fix an error in alambic and ossmeter testing code.
> [export] Remove name and description from alambic and ossmeter formats

- django-prosoul/django_prosoul/settings.py
This code includes 127.0.0.0.1 to the list of allowed hosts.
> [settings] Include 127.0.0.1 to allowed hosts

- django-prosoul/config_deployment.py
- django-prosoul/django_prosoul/settings.py
- docker/docker-compose.yml
- docker/stage
This code extends the list of allowed hosts to include 'wacke.ow2.org'.
> [settings] Add 'wacke.ow2.org' to ALLOWED_HOSTS

- django-prosoul/django_prosoul/templates/base.html
This code removes the link to prosoul.svg, which was leading to 404 HTTP error,
since the image doesn't exist.
> [base] Fix prosoul.svg missing image

- django-prosoul/prosoul/templates/prosoul/editor_metrics.html
- django-prosoul/prosoul/views_editor.py
This PR improves the behavior of the Editor tab:
- This PR add the fetch of the metrics from ElasicSearch (scava-metrics) and show them in the dropdown of Adding/Editing "Metrics" in Prosoul.
- This PR also solves a bug when adding a "Metric" the "Data" attribute is not saved.
> Improve "Editor" tab showing Metrics from the scava ES index

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/templates/prosoul/assessment_config.html
- django-prosoul/prosoul/templates/prosoul/editor.html
- django-prosoul/prosoul/templates/prosoul/editor_attribute.html
- django-prosoul/prosoul/templates/prosoul/visualization_config.html
- django-prosoul/prosoul/views.py
Several improvements have been added:
- Add button has been disabled when a quality model is selected (in Editor tab)
- Deleted useless "Parent" item in Add Attribute form
- Deleted ID in the metrics input select
- Deleted useless inputs in Visualize and Assesment form
- Change link to kibana/dashboards in order to see the dashboards when the quality/assessment panels are created.
> Improvements in forms

- django-prosoul/prosoul/forms.py
The default value will be localhost, as it was before.
This PR is related to https://github.com/crossminer/scava-deployment/issues/44.
> Define ES_URL and KIBITER_URL by a docker env variable

- django-prosoul/prosoul/views_editor.py
This code prevents to query the index METRICS_INDEX when it doesn't exist. The error occurs when using Prosoul before the metrics are imported to ElasticSearch.
When testing https://github.com/crossminer/scava-deployment/pull/45, @MarcioMateus and @mhow2 reported this issue
> [views_editor] Prevent access metric index when doesn't exist

- django-prosoul/prosoul/forms.py
This PR fix the problem when putting "elasticsearch" and "kibiter" on the URLS.
> Remove validators in order to use the docker dependecies tags

- django-prosoul/prosoul/views_editor.py
This code is needed to skip items in METRICS_INDEX which are not metrics. This happens if the original index has been generated before scava-deployment/commit/36297246b1256a020bc62114747c67f20943abb4.
> [views_editor] Skip no metric data

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/setup.py
This code allows to delete and recreate the score index each time the assessment is triggered. This change is needed to allow the user to assess as many as qm he wants given two time intervals. Furthermore a minor change wrt the dependencies in the setup.py has been done to have them listed one per line.
> [prosoul_assess] Delete score index per assessment execution

- docker/stage
This code prevents to clone the prosoul repository when executing the docker-compose, if the repository has been already cloned.
> [docker] Update the stage to prevent cloning

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/views.py
After the addition of the new feature to download single assessment reports, the global one was not working anymore due to a missing parameter in the method `download_csv`. Furthermore this PR fixes also a flake error due to an unused import.
> [views] Fix method signature `download_csv`

- README.md
This code updates the readme by replacing the link to castalia with
the link to the webinar made on March 14th 2019.
> [doc] Remove link to castalia

- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/prosoul_assess.py
This code allows to select the last value of a metric, by leveraging on the top_hit aggregation provided
by ElasticSearch.
> [prosoul] Support for top_hit aggregation

- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/views.py
This code allows to run multiple assessments based on year quarters, the result is stored to the index scava-metrics_scores_by_quarters
> [prosoul] Add support for multiple assessment in the same index

- django-prosoul/prosoul/views_editor.py
As the name is a UID, it isn't necessary to add the user.
This PR fixes #153
> Fix bug when removing quality models

- django-prosoul/prosoul/forms_editor.py
> Require metric name in form when adding/editing a Metric

- django-prosoul/prosoul/views_editor.py
This code allows to define float thresholds for prosoul metrics.
> [prosoul-views_editor] Allow float thresholds

- django-prosoul/setup.py
Pypi requires that the format of the long description for a package is detailed in the variable `long_description_content_type`, in setup.py. Since it now supports Markdown, the conversion to
reST is not needed anymore.
> [setup] Fix format type for long description of package

- django-prosoul/prosoul/prosoul_assess.py
This commit fixes a bug when it is doing the assessment. When the
flag of reverse threshold is active, the array of thresholds will
be reversed and the score will be calculated following the rule
"if less than '<'" instead of "is more than '>'"
---
This PR should fix #171
> [assess] Fix bug when reversed thresholds

- django-prosoul/prosoul/prosoul_assess.py
This code allows to return more than the default number of projects (10) when assessing their quality attributes. Currently this number is now set to 5000.
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
> [prosoul_assess] Increase size of aggregated results

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
This commit adds a visual feature to the assessment dendrogram,
when a metric has not value, now it shows a "no_value" string and
a red color. Moreover, the parent will not take into account this
"no_value" metric and will show the string "( ! )" in order to
notice the user that the assessment is not complete and the
text will be in red color as well.
Examples:
Directly related to #186
> Add "no_value" and visual notification when the metric hasn't value

- django-prosoul/prosoul/prosoul_assess.py
This PR allows to store the empty values obtained from the assessment of the quality models in ES. After calculating the assessment dict, all projects available in ES are retrieved and used to calculate the diff of the assessment dict. It mimics the structure of the assessment dict and it includes only the empty metrics. This operation is applied for quarters and over all the time span of the assessment.
The empty data is stored in ES, in two different indexes. One contains the empty data for quarters, while the other one the empty data for all the time span. Indexes with data and with empty data share the same alias, thus allowing to perform searches on both type of data in a transparent way.
This PR provides also some minor fixes and modifies the logic of the `goals2projects` function, …
> [prosoul_assess] Store empty values to ES

- django-prosoul/prosoul/prosoul_assess.py
This code fixes the dates to calculate the assessment all over the time span selected. Now the dates relies on the variables `from_date` and `to_date`, which
are obtained directly from the form.
Fixes #186
> [prosou_assess] Fix dates to calculate assessment

- django-prosoul/config_deployment.py
- django-prosoul/django_prosoul/create_admin_superuser.py
- django-prosoul/prosoul/admin.py
- django-prosoul/prosoul/apps.py
- django-prosoul/prosoul/data.py
- django-prosoul/prosoul/data_editor.py
- django-prosoul/prosoul/forms.py
- django-prosoul/prosoul/forms_editor.py
- django-prosoul/prosoul/metrics_import.py
- django-prosoul/prosoul/models.py
- django-prosoul/prosoul/prosoul_assess.py
- django-prosoul/prosoul/prosoul_export.py
- django-prosoul/prosoul/prosoul_import.py
- django-prosoul/prosoul/prosoul_metrics.py
- django-prosoul/prosoul/prosoul_utils.py
- django-prosoul/prosoul/prosoul_vis.py
- django-prosoul/prosoul/rest.py
- django-prosoul/prosoul/tests.py
- django-prosoul/prosoul/urls.py
- django-prosoul/prosoul/views.py
- django-prosoul/prosoul/views_editor.py
- django-prosoul/setup.py
This PR has two commits. One is for adding the info for files that don't have it and one for updating the info.
Fixes #13 
I know we have a discussion pending in the grimoirelab repo about the license headers updation, but I updated the authors and years too in this PR. 
@acs @valeriocos 
Can you review this when you are free?
I can squash the two commits if you want. :slightly_smiling_face: 
Please let me know if I have to add or delete anything.
> add license headers and copyright information

- django-prosoul/django_prosoul/templates/registration/login.html
This PR has minor improvements for the Login UI of the application.
**Screenshot** :point_down: 
Please let me know your suggestions. :slightly_smiling_face:
> [UI] Improve the Login UI

- django-prosoul/prosoul/prosoul_assess.py
This code makes sure that the indexes where the assessment data is stored are always created, even when the input data produces empty assessments.
> [prosou_assess] Ensure assessment indexes creation

- django-prosoul/prosoul/templates/prosoul/assessment_config.html
This PR fixes the `TemplateSyntaxError` caused by using `staticfiles` instead of `static` in the templates.
```
{% load staticfiles %} and {% load admin_static %} are deprecated in favor of {% load static %}, which works the same.
```
Ref: https://docs.djangoproject.com/en/2.2/releases/2.1/#features-deprecated-in-2-1
> [assessment] Fix the TemplateSyntaxError
